version: '3'
services:
  chat-service:
    build:
      context: ${WORKSPACE}
      dockerfile: Dockerfile
    image: chat-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/chatmessage?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ZgkLcbgJhKwjknT
    networks:
      - my-network
    links:
      - chat-db
    ports:
      - 8080:8080
networks:
  my-network: