version: '3'
services:
  blog-mysql:
    container_name: blog-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: burak
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./data:/var/lib/mysql

  blog-service:
    restart: always
    build: .
    working_dir: /app
    command: mvn clean spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://blog-mysql:3306/blog?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: burak
    depends_on:
      - blog-mysql
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ~/.m2:/root/.m2