#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27018
#spring.data.mongodb.user = chatdbuser
#spring.data.mongodb.password = PSqPrvulabKbQzA6xTHK0kHvssdvgyEQxMkJoK0107CI7nTPVa
#spring.data.mongodb.database = chatdb
#spring.data.mongodb.authentication-database = chatdb
#server.port=8080
#server.compression.compression=true
#server.compression.min-response-size = 100
#server.compression.mime-types = text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json


spring:
  data:
    mongodb:
      database: chatdb
      port: 27018
      host: localhost
      username: chatdbuser
      password: PSqPrvulabKbQzA6xTHK0kHvssdvgyEQxMkJoK0107CI7nTPVa

jpa:
  properties:
    hibernate:
      ogm:
        datastore:
          create_database=true:
server:
  port: 8080
  compression:
    compression: true
    min-response-size: 100
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json



